/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ClientApp": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "PhotoValidatorFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "PreviewBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "ProcessPhotoQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "SubmissionBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "ThumbnailBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}