/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ClientApp": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "DownloadPresignedFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ExportCaller": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ExportSubmissionsTask": {
      "assignPublicIp": boolean
      "cluster": string
      "containers": any
      "securityGroups": any
      "subnets": any
      "taskDefinition": string
      "type": "sst.aws.Task"
    }
    "ExportsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "GenerateParticipantZipTask": {
      "assignPublicIp": boolean
      "cluster": string
      "containers": any
      "securityGroups": any
      "subnets": any
      "taskDefinition": string
      "type": "sst.aws.Task"
    }
    "MarathonSettingsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MarathonSettingsRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "PreviewBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "PreviewsRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "ProcessPhotoQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "SubmissionBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "SubmissionsRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "ThumbnailBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "ThumbnailsRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "ValidateSubmissionQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "VimmerVPC": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}