/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "SheetGeneratorQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "UploadStatusQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "V2SubmissionsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "V2ThumbnailsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "ValidationQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ZipGeneratorQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}