import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@vimmer/ui/globals.css";
import { Providers } from "./providers";
import { Toaster } from "@vimmer/ui/components/sonner";
import { getSession } from "@/lib/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const generateStaticParams = async () => {
  return [{ locale: "en" }];
};

export default async function RootLayout({
  params,
  children,
}: {
  params: Promise<{ locale: string }>;
  children: React.ReactNode;
}) {
  const { locale } = await params;

  const sessionPromise = getSession();

  return (
    <html lang="en" className="font-neuehaasgrotesk" suppressHydrationWarning>
      <body className={`antialiased`}>
        <Providers locale={locale} sessionPromise={sessionPromise}>
          {children}
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
